# Generated by Django 5.1.2 on 2024-10-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_brewery_phone_alter_brewery_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='type',
            new_name='brewery_type',
        ),
    ]
