# Generated by Django 5.1.2 on 2024-10-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_type_brewery_brewery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='url',
            new_name='website_url',
        ),
    ]
